import type { NormalizedInterface } from '../../normalizer'

/**
 * 生成 Axios 客户端请求函数
 */
export function generateAxiosClient(
  interfaces: NormalizedInterface[],
  importFrom = '@/utils/request',
): string {
  const lines: string[] = [
    `import { request } from '${importFrom}'`,
    `import type { ${interfaces.map((i) => [i.requestType, i.responseType].filter(Boolean).join(', ')).filter(Boolean).join(', ')} } from './types'`,
    '',
    '// ===== Auto-generated by YApi Flow =====',
    '',
  ]

  // Group by category
  const groups = groupBy(interfaces, (i) => i.category || 'common')

  for (const [category, apis] of Object.entries(groups)) {
    lines.push(`// ===== ${category} =====`)
    lines.push('')

    for (const api of apis) {
      const params = api.params.filter((p) => p.location === 'query' || p.location === 'path')
      const hasParams = params.length > 0
      const hasBody = api.method === 'POST' || api.method === 'PUT' || api.method === 'PATCH'

      // JSDoc
      if (api.summary) {
        lines.push(`/** ${api.summary} */`)
      }

      // Function signature
      const args: string[] = []
      if (hasBody && api.requestType) {
        args.push(`data: ${api.requestType}`)
      }
      if (hasParams) {
        args.push(`params: { ${params.map((p) => `${p.name}${p.required ? '' : '?'}: ${p.type}`).join('; ')} }`)
      }

      const returnType = api.responseType ? `Promise<${api.responseType}>` : 'Promise<any>'

      lines.push(`export async function ${api.name}(`)
      if (args.length > 0) {
        lines.push(`  ${args.join(',\n  ')},`)
      }
      lines.push(`): ${returnType} {`)

      // Build request config
      const configParts: string[] = [`    url: '${api.path}'`, `    method: '${api.method}'`]
      if (hasBody && api.requestType) {
        configParts.push('    data,')
      }
      if (hasParams) {
        configParts.push('    params,')
      }

      lines.push(`  return request<${api.responseType || 'any'}>({`)
      lines.push(configParts.join(',\n'))
      lines.push('  })')
      lines.push('}')
      lines.push('')
    }
  }

  return lines.join('\n')
}

/**
 * 生成 Fetch 客户端请求函数
 */
export function generateFetchClient(
  interfaces: NormalizedInterface[],
  baseURL = '/api',
): string {
  const lines: string[] = [
    '// ===== Auto-generated by YApi Flow =====',
    `const BASE_URL = '${baseURL}'`,
    '',
    `import type { ${interfaces.map((i) => [i.requestType, i.responseType].filter(Boolean).join(', ')).filter(Boolean).join(', ')} } from './types'`,
    '',
  ]

  const groups = groupBy(interfaces, (i) => i.category || 'common')

  for (const [category, apis] of Object.entries(groups)) {
    lines.push(`// ===== ${category} =====`)
    lines.push('')

    for (const api of apis) {
      if (api.summary) {
        lines.push(`/** ${api.summary} */`)
      }

      const hasBody = api.method === 'POST' || api.method === 'PUT' || api.method === 'PATCH'
      const args: string[] = []
      if (hasBody && api.requestType) {
        args.push(`data: ${api.requestType}`)
      }

      const returnType = api.responseType ? `Promise<${api.responseType}>` : 'Promise<any>'

      lines.push(`export async function ${api.name}(`)
      if (args.length > 0) lines.push(`  ${args.join(',\n  ')},`)
      lines.push(`): ${returnType} {`)
      lines.push(`  const response = await fetch(\`\${BASE_URL}${api.path}\`, {`)
      lines.push(`    method: '${api.method}',`)

      if (hasBody && api.requestType) {
        lines.push(`    headers: { 'Content-Type': 'application/json' },`)
        lines.push(`    body: JSON.stringify(data),`)
      }

      lines.push('  })')
      lines.push('')
      lines.push('  if (!response.ok) {')
      lines.push("    throw new Error(`API error: ${response.status}`)")
      lines.push('  }')
      lines.push('')
      lines.push(`  return response.json() as ${returnType}`)
      lines.push('}')
      lines.push('')
    }
  }

  return lines.join('\n')
}

function groupBy<T>(items: T[], keyFn: (item: T) => string): Record<string, T[]> {
  const groups: Record<string, T[]> = {}
  for (const item of items) {
    const key = keyFn(item)
    if (!groups[key]) groups[key] = []
    groups[key].push(item)
  }
  return groups
}
