import type { NormalizedInterface, NormalizedField, NormalizedParam } from '../../normalizer'

// ============================================================
// Interface generation - pure functions with template literals
// ============================================================

/**
 * Generate a TypeScript interface definition from a name and fields.
 *
 * Handles:
 *  - JSDoc comments from descriptions
 *  - Optional fields (marked with ?)
 *  - Nested object fields as inline types
 *  - Array types with inline element types
 */
export function generateInterface(
  name: string,
  fields: NormalizedField[],
  description?: string
): string {
  const lines: string[] = []

  // JSDoc header
  if (description) {
    lines.push(`/** ${description} */`)
  }

  lines.push(`export interface ${name} {`)

  // Generate auxiliary interfaces for nested children
  const nested: string[] = []
  const fieldDeclarations: string[] = []

  for (const field of fields) {
    const optional = field.required ? '' : '?'
    let typeName = field.type

    // Handle fields with nested children - generate inline type or separate interface
    if (field.children && field.children.length > 0) {
      if (typeName === 'any' || typeName === 'any[]' || typeName.startsWith('Array<')) {
        // If type wasn't properly set, derive from field name
        if (typeName.startsWith('Array<')) {
          const innerName = typeName.replace(/^Array<|>$/g, '')
          if (!innerName || innerName === 'any') {
            typeName = `${capitalize(field.name)}Item`
          }
        } else {
          typeName = capitalize(field.name)
        }
      }

      // Generate nested interface
      const nestedInterface = generateInterface(typeName, field.children)
      nested.push(nestedInterface)
    }

    // JSDoc for field
    if (field.description) {
      fieldDeclarations.push(`  /** ${field.description} */`)
    }

    fieldDeclarations.push(`  ${field.name}${optional}: ${typeName}`)
  }

  // Add fields to interface body
  lines.push(...fieldDeclarations)
  lines.push('}')

  // Append nested interfaces
  const result = [...lines, '', ...nested].join('\n')

  return result
}

/**
 * Generate all type definitions from normalized interfaces.
 * Produces one file with all request/response interfaces grouped by category.
 */
export function generateTypeDefinitions(
  interfaces: NormalizedInterface[]
): string {
  const lines: string[] = [
    '// ============================================================',
    '// Auto-generated type definitions from YApi',
    '// DO NOT EDIT - generated by @yapi-flow/generator',
    '// ============================================================',
    '',
  ]

  // Group interfaces by category
  const byCategory = new Map<string, NormalizedInterface[]>()
  for (const iface of interfaces) {
    const cat = iface.category || 'default'
    if (!byCategory.has(cat)) {
      byCategory.set(cat, [])
    }
    byCategory.get(cat)!.push(iface)
  }

  // Track generated type names to avoid duplicates
  const generated = new Set<string>()
  const typeBlocks: string[] = []

  for (const [category, ifaces] of byCategory) {
    typeBlocks.push(`// ---- ${category} ----`)
    typeBlocks.push('')

    for (const iface of ifaces) {
      // Generate request interface
      if (iface.requestType && iface.params.length > 0 && !generated.has(iface.requestType)) {
        generated.add(iface.requestType)
        const reqFields = paramsToFields(iface.params)
        const reqDesc = `${iface.method} ${iface.path} - Request`
        typeBlocks.push(generateInterface(iface.requestType, reqFields, reqDesc))
        typeBlocks.push('')
      }

      // Generate response interface
      if (iface.responseType && iface.responseFields.length > 0 && !generated.has(iface.responseType)) {
        generated.add(iface.responseType)
        const respDesc = `${iface.method} ${iface.path} - Response`
        typeBlocks.push(generateInterface(iface.responseType, iface.responseFields, respDesc))
        typeBlocks.push('')
      }
    }

    typeBlocks.push('')
  }

  lines.push(...typeBlocks)

  return lines.join('\n')
}

/**
 * Convert NormalizedParam[] to NormalizedField[] for type generation.
 */
function paramsToFields(params: NormalizedParam[]): NormalizedField[] {
  return params.map((p) => ({
    name: p.name,
    type: p.type,
    required: p.required,
    description: p.description,
    example: p.example,
    children: p.fields,
  }))
}

/**
 * Capitalize the first letter of a string.
 */
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}
